### ISSUE TITLE
0.6 update made all entities unavailable

### ISSUE THREAD

**Issue by kyfehr** [mjoshd/hyperhdr-ha#14]
Updating to 0.6 made all the entities unavailable. I can downgrade to 0.5 but it will only work for a while before becoming unresponsive when triggering an entity.

**Comment by mjoshd** [comment]
I've not experienced anything like that so I'm really not sure what to suggest.

I was using 0.0.6 for almost two weeks before releasing it and didn't experience any issues, nor have I run into any since then.

The only thing I can think of is to make sure that your Home Assistant is fully updated (Core-2022.5.5 & OS-8.1 as of today). 

I have read, in the HA forums, that some people were having issues with entities randomly disappearing after they upgraded to HA OS 8.0 but that has apparently been addressed in the 8.1 release.

**Comment by kyfehr** [comment]
Yes upgrading HA fixed the issue. Needed to remove and readd the integration, but appears to be working as intended again. Sorry should have tried that first.
