### ISSUE TITLE
I can't find Hyper HDR in HACS/Integrations

### ISSUE THREAD

**Issue by Pastaloverzzz** [mjoshd/hyperhdr-ha#29]
I can't find Hyper HDR in home assistant, searched HACS and integrations. (This is my first install of hyperHDR)

I can only find Hyperion in the integrations and when i type hyper in HACS i only find the integration "hypervolt charger"

Core
2024.10.3
Supervisor
2024.10.3
Operating System
13.2
Frontend
20241002.3

**Comment by cameronkelley** [comment]
You have to add it as a custom repository since it's not in the default HACS repo.

1. Go to HACS and hit the three dots on the top right
2. Tap "Custom repositories"
3. Enter "mjoshd/hyperhdr-ha" in the repository field
4. Select "Integration" as the type
5. Click add

It should show up immediately after that. Funny enough I just did this a few minutes ago as I'm setting up a new test HA server.

![Screenshot_20241028_101857_Home Assistant](https://github.com/user-attachments/assets/12fe4050-b80f-40fd-98ed-05c50e32bb75)

**Comment by Pastaloverzzz** [comment]
Jep, i'm dumb. Already installed it manually, didn't know you could add custom repositories like that.
