### ISSUE TITLE
HyperHDR not in the configurable Integration list

### ISSUE THREAD

**Issue by bfbones** [mjoshd/hyperhdr-ha#7]
Got the same Problem as https://github.com/mjoshd/hyperhdr-ha/issues/1

## Version of the custom_component
0.0.5

## Configuration
Configuration not working.

## Describe the bug
Using HA 2022.2.5 same results, HyperHDR isn't in the list.
Also not after trying 0.0.4, 0.0.2 nor restarting HA multiple times or simply waiting for hours.

Something's still wrong with that config routine.

Can you have a look?
Is there a way to configure it manually?

## Debug log
I've checked the logs, there's nothing obvious, only that I have the custom component installed.

**Comment by mjoshd** [comment]
Closing since I haven't heard back in more than 2 weeks.

**Comment by GamerX06** [comment]
I am having this same issue and I have a few other custom repos i haven't had any issues with.

**Comment by mjoshd** [comment]
Are you saying that it appeared in the list 10 minutes after rebooting? If so, that is very strange and I'm not sure what to tell you.

I performed a few tests using both a physical machine (old laptop with Home Assistant OS) and a virtual machine (Home Assistant OS in Hyper-V) but I cannot replicate your issue.

Did HACS place the files inside the `custom_components` directory?

Using HACS, I have completely uninstalled, rebooted, reinstalled, rebooted and it appears in the integration list without issue.

I even tried a manual preparation where I just placed the `hyperhdr` directory inside `custom_components` (e.g. `\config\custom_components\hyperhdr`) using a file manager and, after a reboot, it again appeared in the integration list without issue. 

The only other thing I can think of is if something is blocking your Home Assistant from getting the required python repo, that could potentially prevent it from showing up and/or working correctly.

Make sure there is nothing on your network that is blocking/filtering Home Assistant such as PiHole, AdGuard, PFSense, etc. and maybe adjust your Home Assistant DNS settings to have multiple addresses; I use 3 in the DNS Servers field `1.1.1.1, 9.9.9.9, 8.8.8.8` for resiliency.

If all else fails, please set up test environment with a completely fresh Home Assistant installation (100% stock/default settings, do not restore a backup) on a VM or old computer/laptop and just copy the `hyperhdr` directory inside of `custom_components` then reboot and check to see if it appears in the integrations list.

**Comment by bfbones** [comment]
You repeat yourself again and again throughout that repo after every statement about that problem. It's always working from your side. I can already count 5-10 people having that problem and out of my view your integration is the only one having such problems.
Further saying that they should try running a fresh installation is not a working solution. As you may know a grown up home assistant is a shitload of work, so nobody will reset a complete HA instance only to be able to use your integration.

Sorry for that direct words, but you help nobody with your novel of "it works on my side". Maybe offer more ideas how the people can debug that problem on their (not working ) side.

**Comment by mjoshd** [comment]
Hi @bfbones, 
If you are displeased with my repo then please feel free to create a fork, make any changes you like, and manage it however you see fit.

I 100% understand how much work goes into creating/maintaining a Home Assistant installation. I also 100% understand that Home Assistant is super customizable and that's what I'm getting at; perhaps it's user-customization that is causing the failure.

Testing on a completely clean/stock installation is the best next step in this instance.

I cannot reproduce the issue which you, and a hand-full of others, describe.

I can, however, install/configure/run/uninstall/re-install/re-configure/re-run/etc/etc without issue on my main system, which has been in use for over 3 years, and every test system I've set up (both physical & virtual); I'm sorry if this upsets you but it's true.

In my previous reply I did describe a way to _**test with a fresh installation**_ without making any changes to a user's existing installation, using a spare computer or virtual machine, which would help to eliminate the possibility that something in their 'grown up' configuration is the root cause.

If it works on a fresh installation, it is then a matter of the user checking what differences exist between a fresh installation and their own, user-customized configuration that could be causing the issue.

If it does not work on a fresh installation then the issue is likely network related as I have already tested it with Home Assistant Operating System on a Raspberry Pi4, x86-64 computer (old laptop), and virtual machine (Hyper-V) which rules out general hardware/platform incompatibility.

Again, if you are displeased or unhappy with the custom_component/integration that I forked from the Hyperion component/integration code, created for my personal use, and made available to others to use freely at no charge, and with no guarantee or warranty, then please do create a fork of this repo, make any changes you like, and manage it how you see fit.
