### ISSUE TITLE
Automatic Source Switching

### ISSUE THREAD

**Issue by namoi2000** [mjoshd/hyperhdr-ha#8]
Hi,

I am currently experiencing an issue using HyperHDR Beta8 and Home Assistant.
I have created a button to switch the leds on/off.
Problem is, when I click it, the source ultimately switches from Flatbuffer Webos to Home Assistant (not immediately though). I tried to turn off auto selection off but it doesn't work on the long run.

Any idea what could be wrong ?

Thanks

**Comment by mjoshd** [comment]
Sorry, not really sure what the issue would be. 

HyperHDR v18 isn't even available as a beta on the releases page yet so I would assume there will be some bugs with unreleased sowftware.

Sounds like you may be using a rooted TV as the source? If so, that is far outside my area of knowledge. I only have experience using various HDMI grabbers like the ezcap320. Maybe setting a lower priority for HA or a higher priority for your TV?

I have noticed some strange behavior even with v17 until you [uncheck a couple boxes as listed on the Wiki > Post-setup Advice](https://github.com/mjoshd/hyperhdr-ha/wiki#post-setup-advice).

Give that a try then restart Home Assistant and see if the situation is improved.

Either way, I don't intend to try chasing down any issues with v18 until it is released as stable.

Closing since v18 is not yet available as a stable release.
