### ISSUE TITLE
Host unreachable after Power Loss

### ISSUE THREAD

**Issue by Hilpas** [mjoshd/hyperhdr-ha#9]
Hi,

i have an problem with the integration. Initially everything works flawlessly but as soon as i unplug the PI running HyperHDR during the night and turn it back on it says host unreachable if i try to control it. I never gets controllable again until i delete an reconfigure the integration. Its configured via hostname, its not the IP that is changing i have checked that aleady. Its controllable via its own webinterface no problem.

Any idea?

**Comment by mjoshd** [comment]
My initial thought would be to simply not unplug the RPi at night. They barely use any power when sitting idle. If you use the toggle in HA to turn off USB Capture then it will drop down to very few watts.

If that's not an option then an alternative to deleting & re-adding the integration would be to restart Home Assistant (just restart HA, not the Host machine). This usually doesn't take much time and will cause it to rediscover the HyperHDR as long as the IP is the same. I can't speak to how well it will work or not when configured by hostname instead of IP as that will have more to do with your own network, mDNS, etc. 

The thing is, when Home Assistant can't reach a configured device it usually retries at longer and longer intervals until it gives up completely, after which I do not know how to kick off discovery again without restarting HA.

**Comment by mjoshd** [comment]
Two weeks with no reply. Closing.
